services:
  # The Web Service (Django Application)
  - type: web
    name: talentorbit-web
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py createsu"
    startCommand: "gunicorn talentorbit.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: talentorbit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-render-url.onrender.com" # You will replace this later
      # Razorpay and Email vars will be added manually in Render Dashboard for security
      # Cloudinary vars will be added manually in Render Dashboard for security

databases:
  # The Managed PostgreSQL Database
  - name: talentorbit-db
    region: ohio
    plan: free
    databaseName: talentorbit
    user: talentorbit_user
