# Generated by Django 6.0.2 on 2026-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skill_alter_companyprofile_logo_alter_job_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.skill'),
        ),
    ]
