# Generated by Django 6.0.2 on 2026-02-17 14:35

from django.db import migrations, models


def set_existing_users_verified(apps, schema_editor):
    """Mark all existing users as email-verified (they pre-date this feature)."""
    User = apps.get_model('core', 'User')
    User.objects.all().update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_users_verified, migrations.RunPython.noop),
    ]
