# Generated by Django 6.0.2 on 2026-02-17 15:17

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_withdrawn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[core.utils.validate_file_extension, core.utils.validate_file_size, core.utils.validate_content_type]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[core.utils.validate_file_extension, core.utils.validate_file_size, core.utils.validate_content_type]),
        ),
        migrations.AlterField(
            model_name='skillvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', validators=[core.utils.validate_file_extension, core.utils.validate_file_size, core.utils.validate_content_type]),
        ),
        migrations.AlterField(
            model_name='skillvideo',
            name='video_file',
            field=models.FileField(upload_to='skill_videos/', validators=[core.utils.validate_file_extension, core.utils.validate_file_size, core.utils.validate_content_type]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[core.utils.validate_file_extension, core.utils.validate_file_size, core.utils.validate_content_type]),
        ),
    ]
